#ifndef TILES_H
#define TILES_H

#include "Constants.h"

extern char COVERED[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char UNCOVERED[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char MINE[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char FLAG[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char ONE[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char TWO[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char THREE[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char FOUR[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char FIVE[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char SIX[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char SEVEN[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char EIGHT[CELL_SIZE_PIXEL][CELL_SIZE_PIXEL];
extern char GLASSES[SMILE_SIZE][SMILE_SIZE];
extern char SAD[SMILE_SIZE][SMILE_SIZE];

#endif
